AWSTemplateFormatVersion: "2010-09-09"


Parameters:
  ImageId:
    Type: String
    Default: ami-08e4e35cccc6189f4
    

  InstanceType:
    Type: String
    Default: t2.micro

MyEC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: !Ref ImageId
    InstanceType: !Ref InstanceType
    Tags:
      - Key: Name
        Value: ismaeel-cloudformation-Server    
