AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ImageId:
    Type: String
    default : ami:3asda45324233
  InstanceType:
    Type: String
    default: t2.medium
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      Tags:
        - Key: Name
          Value: ismaeel-cloudformation-Server    
